version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_nest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: teste-fullstack
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d teste-fullstack -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  nestapp:
    volumes:
      - ./:/app
    build:
      context: .
      target: development
    container_name: nest_backend
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      DB_NAME: teste-fullstack

volumes:
  pgdata:
